export const URI_GET_CHARACTERS = '/v1/public/characters'

export const FETCH_CHARACTER = 'FETCH_CHARACTER'
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS'
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS'

export const UPDATE_CHARACTER = 'UPDATE_CHARACTER'
export const UPDATE_CHARACTER_SUCCESS = 'UPDATE_CHARACTER_SUCCESS'
